package com.allianz.healthtourismagency.model.enums;

public enum HospitalDepartmentEnum {

    INTERNAL_MEDICINE, PEDIATRICS, OBSTETRICS_AND_GYNECOLOGY, CARDIOLOGY, DERMATOLOGY, NEUROLOGY, PSYCHIATRY,
    ORTHOPEDICS, GASTROENTEROLOGY, UROLOGY, ENDOCRINOLOGY, PULMONOLOGY, ONCOLOGY, NEPHROLOGY, INFECTIOUS_DISEASE,
    RHEUMATOLOGY, OPHTHALMOLOGY, OTOLARYNGOLOGY, RADIOLOGY, REHABILITATION;

}
